### ISSUE TITLE
JAR task

### ISSUE THREAD

**Issue by mnn** [UdashFramework/udash-generator#22]
In my opinion until Udash has easy generation of jar for deployment, it's not ready for serious use. I have unsuccessfully battled with this and I am by no means total beginner. Guys at gitter tried to help me, but to no avail. I have tried every suggestion and was not able to get it working jar (issues with paths, not bundling FE part and so on). While it's possible to use the SBT, it's very cumbersome to use it as a launcher (e.g. my VPS has only 1GB of memory, so compilation is crashing on OOM very often) and it's not really a way of running an application in a production (a lot of wasted memory, useless things from production server perspective like compiler and SBT). This is a show-stopper for me and I think for many others as well.

**Comment by Starzu** [comment]
@mnn Take a look at https://github.com/UdashFramework/udash.g8 - I want to replace the old Udash Generator with this template after 0.6 release. This project contains a basic `sbt-native-packager` configuration for creating a zip package with your application. Give it a try and let me know what you think about it.

**Comment by mnn** [comment]
It looks great and the readme file is nice. Unfortunatelly I wasn't able to make the packaging working (no modifications were made, this is straight from the generator). Or is some further configuration required?

```
sbt packager/universal:packageBin
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /xxx/workspace/scala/udash_g8_test/my-udash-application/project
[info] Loading settings from build.sbt ...
[info] Set current project to my-udash-application (in build file:/xxx/workspace/scala/udash_g8_test/my-udash-application/)
[info] Packaging /xxx/workspace/scala/udash_g8_test/my-udash-application/packager/target/scala-2.12/my-udash-application-bootstrapping-test_2.12-0.1.0-SNAPSHOT-sources.jar ...
[info] Done packaging.
[info] Wrote /xxx/workspace/scala/udash_g8_test/my-udash-application/packager/target/scala-2.12/my-udash-application-bootstrapping-test_2.12-0.1.0-SNAPSHOT.pom
[info] Packaging /xxx/workspace/scala/udash_g8_test/my-udash-application/packager/target/scala-2.12/my-udash-application-bootstrapping-test_2.12-0.1.0-SNAPSHOT-javadoc.jar ...
[info] Done packaging.
[info] Packaging /xxx/workspace/scala/udash_g8_test/my-udash-application/packager/target/scala-2.12/my-udash-application-bootstrapping-test_2.12-0.1.0-SNAPSHOT.jar ...
[info] Done packaging.
[info] Wrote /xxx/workspace/scala/udash_g8_test/my-udash-application/shared/.jvm/target/scala-2.12/my-udash-application-shared_2.12-0.1.0-SNAPSHOT.pom
[info] Packaging /xxx/workspace/scala/udash_g8_test/my-udash-application/shared/.jvm/target/scala-2.12/my-udash-application-shared_2.12-0.1.0-SNAPSHOT-sources.jar ...
[info] Done packaging.
[info] Main Scala API documentation to /xxx/workspace/scala/udash_g8_test/my-udash-application/shared/.jvm/target/scala-2.12/api...
[info] Running io.company.app.backend.css.CssRenderer /xxx/workspace/scala/udash_g8_test/my-udash-application/frontend/target/UdashStatics/WebContent/styles false
model contains 53 documentable templates
[error] /xxx/workspace/scala/udash_g8_test/my-udash-application/shared/src/main/scala/io/company/app/shared/rpc/server/MainServerRPC.scala:14:3: Could not find any member to link for "SecureRPC".
[error]   /** Verifies provided UserToken and returns a [[SecureRPC]] if the token is valid. */
[error]   ^
[error] one error found
[error] (sharedJVM / Compile / doc) Scaladoc generation failed
[error] Total time: 12 s, completed Feb 2, 2018 2:55:11 PM
```

I am using SBT 1.1.0.

**Comment by Starzu** [comment]
@mnn It was a bug. Just replace `[[SecureRPC]]` with `[[io.company.app.shared.rpc.server.secure.SecureRPC]]`. It's also fixed in the template: https://github.com/UdashFramework/udash.g8/commit/8abac2a9f87bbae34a64b8312bb46d4c85319619#diff-43624c933b651c0565776916e42eb186

**Comment by mnn** [comment]
Getting one step closer - now packaging is successful, but when I copy the archive, unpack it and run the generated script, BE is running, but it seems FE is not being present. BE on 9090 returns 404:

```
HTTP ERROR 404
Problem accessing /. Reason:

    Not Found
Powered by Jetty:// 9.4.8.v20171121
```

Does FE need to be copied manually? Or maybe it needs to be build at least one time before trying packaging task?

**Comment by Starzu** [comment]
@mnn You should execute the launcher script from the root directory of the project (like: `./bin/script`), because in the server configuration we pass a relative path (`statics = "UdashStatics/WebContent"`) to the static frontend files.

**Comment by mnn** [comment]
@Starzu Thanks, now everything works :smile:.
